### ISSUE TITLE
Endless scrolling through the playlist

### ISSUE THREAD

**Issue by MattSkar** [stefanpaduraru/playlist-randomizer#11]
A recent issue has appeared when I try to use the site. Instead of playing the playlist, it'll endlessly scroll through all the songs without playing anything. Is this on my side or is the site bugged for everyone?

**Comment by stefanpaduraru** [comment]
@ThePiggu
Hello. Thanks for raising this issue. I've got this feedback from an other user, but have yet to identify what causes it.
If the yt player reports a playback error, the app automatically navigates to the next item in the playlist.
Could you open up the dev console and send me screenshots of the console and network tabs? Thx
