### ISSUE TITLE
Website has been down for last couple of days

### ISSUE THREAD

**Issue by shinsean** [stefanpaduraru/playlist-randomizer#16]
The website has been down for me for the last two days.
[This](https://imgur.com/a/Uv2xpeB) is the error message I get when I get on the website.

I have tested it on four different browsers and they all reported the same issue with the same error page. The browsers are listed below:
Firefox Developer Edition (up-to-date)
Firefox (one minor update behind)
Chrome (up-to-date)
Stargon (mobile browser built using Chromium) (up-to-date).

**Comment by Borinius** [comment]
Getting this on my end aswell running firefox latest.

**Comment by smasher-101** [comment]
I tried on vivaldi and firefox and on both browsers I get an error.

**Comment by shinsean** [comment]
The website is loading for me now. Unsure if this is just for me or it has also been fixed for other people.
