### ISSUE TITLE
[Feature Request] Combine Multiple Playlists for Randomization

### ISSUE THREAD

**Issue by joro8425** [stefanpaduraru/playlist-randomizer#17]
Hey There, 
I love the site, and appreciate all your hard work. This certainly isn't an issue I'm reporting, but a feature I would hope to see added in the future. 
I have been making playlists of music for 10 years now and have 22 such playlists. The amount of videos in the playlists exceeds the 5000 video limit, and I am constantly making more. In addition, I enjoy keeping the playlists limited to 200 videos for organizational purposes and because that was the video cap back in the day. 
If it would be possible to add a functionality to your program that allows a person to select multiple playlists and randomize the videos between them, I would be eternally grateful. 
Thank you again for your work on this. 

All the best.

**Comment by stefanpaduraru** [comment]
Hello. This is the top feature on my to-do list. But it involves quite some work so it'll take some time. Stay tuned.

**Comment by stefanpaduraru** [comment]
Done.
