### ISSUE TITLE
Could not load playlist.

### ISSUE THREAD

**Issue by NooberPlays** [stefanpaduraru/playlist-randomizer#30]
Anyone else having this issue? it just says "Could not load playlist." after pasting the playlist link and clicking "go"
![image](https://user-images.githubusercontent.com/62673966/136583233-1d5d8aa2-bc1f-44b6-b9cb-af80451d8c4b.png)

**Comment by Gakurankuran** [comment]
It's been happening to me too since like 5 or 6 days ago. A not-so-good solution I've found is to just keep checking the page at random times, but the chance of that working seems to be low.

**Comment by NooberPlays** [comment]
> It's been happening to me too since like 5 or 6 days ago. A not-so-good solution I've found is to just keep checking the page at random times, but the chance of that working seems to be low.

Hmmmm I see, I remember reading at the repository that it is hosted on heroku and therefore it might be down when you try to use it but I'm not sure if this is the case

**Comment by JasonBaby87** [comment]
More specifically, this happens when I try to update a playlist or add a new playlist. Existing playlists still work. But I deleted the existing one because I thought that might help :weary:

**Comment by JasonBaby87** [comment]
Here is the Chrome console log. I think it got error 403.
[www.playlist-randomizer.com-1633835552708.log](https://github.com/stefanpaduraru/playlist-randomizer/files/7316763/www.playlist-randomizer.com-1633835552708.log)

**Comment by NooberPlays** [comment]
This is the log I get when trying to load the playlist 
[www.playlist-randomizer.com-1633838809852.log](https://github.com/stefanpaduraru/playlist-randomizer/files/7316830/www.playlist-randomizer.com-1633838809852.log)

**Comment by Gakurankuran** [comment]
The page seems to be working again!

**Comment by NooberPlays** [comment]
> The page seems to be working again!

Seems like it, I am using it right now, hopefully won't happen again

**Comment by smasher-101** [comment]
Can confirm that it is working for me as well.
