### ISSUE TITLE
Enable/Disable background changes

### ISSUE THREAD

**Issue by plague42** [stefanpaduraru/playlist-randomizer#6]
Love the program, does exactly what it needs and way better than youtube's!

Before this I used the Valami one, until it didn't work anymore, but one cool functionality of it was to customize font and background color. It wasn't picture customization, but rather color only, and I kinda miss that.

It could be considered more of a suggestion than an issue, but then again the background change at every video makes my browser (firefox) freeze for some seconds, and the music stutters too. Only way I've found currently is to "inspect element" and disable the background, making it bright white (but it solves the freeze and stuttering issues).

Line:
<div class="background absolute-fullscreen">

Thanks for your work! I'd love to help, but I know next to nothing in coding :/

**Comment by stefanpaduraru** [comment]
Hi,

Thanks for the suggestion 👍 . I'll include a toggle for that in the near future. Cheers

**Comment by stefanpaduraru** [comment]
https://github.com/stefanpaduraru/playlist-randomizer/pull/8
